Om een startdiskette voor de PCW8512 of PCW8256DD met extra 256 K RAM klaar te maken :

1. Kopieer de hulpprogramma's PIP,SUBMIT,BASIC en SETKEYS van de systeemdiskette
   naar een geformatteerde diskette in drive B: (boekhoudstartdisk).  Zorg ervoor
   dat de systeemdiskette 1 kant 2 zich in drive A: bevindt.

   pip
   b:=a:pip.com
   b:=a:submit.com
   b:=a:basic.com
   b:=a:setkeys.com

2. Verwijder de WRITE PROTECTION van de distributiediskette

3. Breng de distributiediskette kant A in drive A en druk 'B:SUBMIT A:8512A'

4. Steek de distributiediskette kant B in drive A en druk 'B:submit A:8512B'

5. De startdiskette van het boekhoudpakket is nu klaar.
   Berg de distributiediskette van het boekhoudpakket op een veilige plaats op.

Bij mogelijke problemen neem gerust kontakt op met :   VSOFT - AALST
                                                       HARDINGSTRAAT 8
                                                       9390 AALST-HERDERSEM
                                                       TEL:053/772784

of met uw plaatselijke dealer.  Succes !
-HERDERSEM
                                    